### ISSUE TITLE
Firmware update is non-adivsed.

### ISSUE THREAD

**Issue by dschaper** [jprochazka/adsb-feeder#51]
Running a firmware update is not advised for most installations. The command updates firmware to bleeding-edge and may (read as often) cause issues. (Right now the foundation is testing a new sdcard reading algorithm and that can cause problems with some manufacturers.) The latest stable firmware is released as a package that comes down via a routine apt-get so the old way of rpi-update has been depreciated.

**Comment by jprochazka** [comment]
I was honestly planning on stripping out the option period due to the fact as you stated apt now handles firmware updates as well.

This was added back when the scripts were first conceived and at the time I went off the information in this post announcing the tool used to update the firmware. They did not mention anything about this installing alpha or beta firmware at the time.
https://www.raspberrypi.org/blog/easy-firmware-updating-tool-from-hexxeh/

If rpi-update does in fact install more up to date bleeding edge software I may leave the option in for those interested in the latest and greatest as I some times am. This step has always been optional and if remains in the scripts after the cleanup I will better label the option to reflect your concerns.

**Comment by dschaper** [comment]
I remember the days when firmware update was almost a requirement. It's changed, and of course I can't find the latest update over in the Raspi Forums, but there's one here about rpi-update now pulling a testing version of 4.4 kernel (https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=130429). Leaving it would be fine as long as the end users know that breakage is likely and support should be handled over in the Raspi Forums if the Pi's suddenly stop booting...

**Comment by jprochazka** [comment]
Indeed.

**Comment by jprochazka** [comment]
Ended up removing the option in commit 8e24da42ff084ae6688d3f0307a73c81286b76dd.
