### ISSUE TITLE
Something went wrong with commit "Conflict resolution."

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#81]
There are sections in the sh like this:
<<<<<<< HEAD
<<<<<<< HEAD
  "LINE1:messages#0000FF:Messages Received" \
  "LINE1:min#FFFF99" \
  "AREA:maxarea#FFFF99:Min/Max:STACK" \
  "LINE1:7dayaverage#00FF00:7 Day Average" \
  "LINE1:messages#0000FF" \
  "AREA:y2strong#FF0000:Messages > -3dBFS/Hr (RHS)" \
  "LINE1:y2positions#00c0FF:Positions/Hr (RHS)\c" \
=======
  "LINE1:min#FFFF99:mins" \
  "AREA:maxarea#FFFF99:max:STACK" \
  "LINE1:7dayaverage#00FF00:7 Day Average" \
  "AREA:y2strong#FF0000:messages >-3dBFS/Hr (RHS)" \
  "LINE1:y2positions#00c0FF:Positions/Hr (RHS)" \
  "LINE1:messages#0000FF:Messages Received\c" \
>>>>>>> 82576755a77e5581c4fedd3e1ee0bad45cadc064
=======
  "LINE1:min#FFFF99:mins" \
  "AREA:maxarea#FFFF99:max:STACK" \
  "LINE1:7dayaverage#00FF00:7 Day Average" \
  "AREA:y2strong#FF0000:messages >-3dBFS/Hr (RHS)" \
  "LINE1:y2positions#00c0FF:Positions/Hr (RHS)" \
  "LINE1:messages#0000FF:Messages Received" \
>>>>>>> 0825d25e6c782511daa9f29c5d51136ea2666882

I don't know too much about GitHub to know what went wrong and how to fix it. Also, I'm away from the Pi where I did the recent work so I don't have the original and good file handy right now.

**Comment by mgunther68** [comment]
Pull request #82 should fix the file.

**Comment by jprochazka** [comment]
Looks like an error on my part I had a merge conflict when merging the requests and apparently missed one before committing the file. I merged your pull requests in the wrong order and ended up with conflicts in the end hence the mass of commits addressing the same thing made on the 2nd.

Please review the final product I just fixed in commit aff126bea9f8611617dd100f039692d351214221. Let me know if you see anything out of place.

As far as originals your changes can be found in the following commits:
96d8e2aa1a313135cf49db09d65a539377cff293
3a192df07c1065fb74e8c2835f04aafa57211f30
02a453f9dc066f35fd4901ef465a43f088243534

It appears I have a failing amp on my feeder. I have not received much if any data over the air since Friday so I did not test the changes. I know that's a not a good thing to do but took it for granted I merged things properly which I did not apparently... Anyways last night as soon as a storm hit the area feeder began picking aircraft up again so I will be sure to check things out this evening. Go figure a storm fixed things instead of breaking them!

In the mean time if everything looks good on your end let me know and I will close out the issue.

**Comment by mgunther68** [comment]
Yeah no worries. Ran an update on my second Pi and all looks good. Guess this can be closed.
