### ISSUE TITLE
Add option for dump1090-mutability to bind to all interfaces

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#91]
Currently, after installation of dump1090-mutability, it is set to bind to interface 127.0.0.1 (i.e. localhost) only. This is fine for all software that is installed with the script but may present issues when user adds more software that needs to connect to the Pi IP address rather than localhost. Example: VRS on separate Windows host that wants to connect to [Pi IP]:30005
This will not work without manually reconfiguring dump1090.

I can see 3 possible options here:

1. Just a warning/info for user to reconfigure dump1090 manually if required (however, this may be overlooked by some users)
2. Present a choice during installation to keep the default 127.0.0.1 or have a blank parameter (meaning it will bind to all interfaces)
3. Configure dump1090 to bind to all interfaces by default

**Comment by fatherdoctor** [comment]
I'd almost prefer if dpkg-reconfigure dump1090-mutability was run after installation so that all of the native options were presented to the user after all of the other scripting is set up.

**Comment by mgunther68** [comment]
That would work for me as well.

**Comment by jprochazka** [comment]
I have thought about this in the past especially being I like to connect to my receiver sometimes from work using VRS. I originally decided against opening to other interfaces due to the fact not everyone realizes the ramifications of doing so and I would hate to see someone's device or worse yet network taken down unknowingly because a vulnerability was found later on.

I could see giving an option to run dpkg-reconfigure but there again not everyone using the image or scripts is all that knowledgeable which leads to fouled up settings and "why does this not work now?" questions. Seems most people who are knowledgeable when it comes to dump1090-mutability realizes this option is available.

None of this means it is written in stone I would not make these changes just wanted to pose some different views which lead to their absence in the first place to get thoughts and feedback on the reasoning before considering them.

**Comment by mgunther68** [comment]
Yes, all valid reasons. Maybe display a prominent message, addressed to "Advanced Users", to run the dpkg-reconfigure manually if you need to access dump1090 from anything other than localhost?

My reason for bringing it up is that I helped someone via private forum messages to set up everything, incl. VRS and there he did not understand why it did not work out-of-the box. I told him to run the dpkg-reconfigure.

**Comment by fatherdoctor** [comment]
Joe, it actually stumped me for a while. I spent (embarrassed to admit) probably over two hours trying to figure out why the port forwarding on my router wasn't working for the remote Mlat group I participate in.

I definitely get the point about not wanting to endanger typical users though. Maybe adding an advanced menu is the way to go as it could be used as a jumping point for all kinds of feature creep in the future. dpkg-reconfigure dump1090-mutability would just be a start!

**Comment by jprochazka** [comment]
Added option to bind dump1090-mutability to all IP addresses. Changes were pushed to template branch and will be merged with master once the branch has been completed and tested.
